FROM node:20-alpine3.19

WORKDIR /usr/src/app

RUN apk add --no-cache curl

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .
# Para entorno de produccion copiar los archivos proto desde el contexto principal
# (confirmar tener ../proto relativo correcto en la estructura)
# COPY ../proto ./proto

EXPOSE 4000
