-- AlterTable
ALTER TABLE "Driver" ALTER COLUMN "birthDate" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "isAvailable" SET DEFAULT true,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "license" DROP NOT NULL;
