global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'drivers-ms'
    metrics_path: /metrics
    static_configs:
      - targets: ['drivers-ms:9103']

  - job_name: 'vehicles-ms'
    metrics_path: /metrics
    static_configs:
      - targets: ['vehicles-ms:9104']

  - job_name: 'auth-ms'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-ms:9102']
  
  - job_name: 'api-gateway'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['api-gateway:4000']
