apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: routes-ms
  name: routes-ms
spec:
  ports:
  - name: "5003"
    port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    app: routes-ms
  type: ClusterIP
status:
  loadBalancer: {}
